
services:
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/root/redis
    environment:
      - REDIS_PASSWORD=z123456
      - REDIS_PORT=6379
